### ISSUE TITLE
Shift+click on rewards only works if you hold shift *before* you drag the mouse cursor over the reward.

### ISSUE THREAD

**Issue by chevex** [Lanrutcon/CatchTheWind#17] opened 2016-09-10 20:47 UTC
If you are already moused over a reward and showing the item's tooltip then pressing shift does nothing. I've been pressing F10 today when rewards pop up so I can compare stats to the gear I'm wearing. Then suddenly one time I saw the comparison tooltip but couldn't get it back so I stopped and messed with it for a bit.

Turns out you can show the comparison tooltip reliably if you hold SHIFT first and *then* drag the mouse over the reward. It will then show the item tooltip and the comparison tooltip. It just doesn't work if your mouse is already there and *then* you press SHIFT.

**Comment by benoitheylens** [comment] 2016-09-11 05:49
I think to avoid mistakes you could maybe show the tooltip whenever you press shift and your mouse is on the reward (as it works in default UI. It's not very important but could lead new adopters to think there is a bug or a misconception instead of a nice feature ;).

**Comment by chevex** [comment] 2016-09-11 17:14
I don't think he intended this to work this way. I assume he would classify this behavior as a bug which is why I reported it here :)

**Comment by chevex** [comment] 2016-09-11 17:56
Now that I've been viewing tooltips properly I've been occasionally getting a positioning bug where the comparison tooltip appears off to the bottom right and this LUA error pops up:

```lua
Message: Interface\AddOns\CatchTheWind\Utils.lua:108: ShoppingTooltip2:SetPoint(): ShoppingTooltip1 is dependent on this
Time: 09/11/16 11:55:30
Count: 4
Stack: [C]: in function `SetPoint'
Interface\AddOns\CatchTheWind\Utils.lua:108: in function `CTW_GameTooltip_ShowCompareItem'
[string "*:OnEnter"]:12: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = ShoppingTooltip2 {
 0 = <userdata>
 updateTooltip = 0.2
 needsReset = true
}
(*temporary) = "TOPLEFT"
(*temporary) = ShoppingTooltip1 {
 0 = <userdata>
 updateTooltip = 0.2
 needsReset = true
}
(*temporary) = "TOPLEFT"
(*temporary) = 0
(*temporary) = 185.99110412598
```

**Comment by chevex** [comment] 2016-09-11 22:02
Video of tooltip bug.

https://youtu.be/jS-hkqZ5-ww

**Comment by Lanrutcon** [comment] 2016-09-12 19:26
Thank you very much for the video. It's the best way to show what is happening to another person.
Screenshots are also very good and in some causes are more than enough.
Words can do the job, in most cases, but if the problem is too "complicated" then opt to take a screenshot or a video.

I'll see what's going tomorrow and I hope to release a new version (new stuff + bugfixes) in the next couple of days.

Thanks once again.

**Comment by chevex** [comment] 2016-09-12 19:33
np, I'm sure you'll see more from me as I continue to use it :P

**Comment by Lanrutcon** [comment] 2016-09-15 20:39
Thanks for the tip. I also use Xbox app to record my videos: good quality and the file size are pretty small - more than enough that . I didn't know about that shortcut, the "simple" **Windows Key + Alt + R** to start&stop record, but that one should come in handy in some situations.

Going back to the topic. This bug should be fixed in: https://github.com/Lanrutcon/CatchTheWind/commit/18e47d190f0a967307f764c209d08ef3e8f2adc1

Thanks for reporting.

**Closed by Lanrutcon** 2016-09-15 20:39 UTC

**Comment by chevex** [comment] 2016-09-15 20:41
You can increase the video quality in settings if you want higher def.

Thanks for the fix!
