### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by benoitheylens** [Lanrutcon/CatchTheWind#11] opened 2016-09-04 10:50 UTC
In Azsuna, when we go to the ship of Sylvanas and click on the chest, the addon freeze the game, then you can't take the quest, no clicking work anymore, and you see everything you type in chat while moving.

When I press Z to move forward (azerty keyboard), It shows "zzzzzzzzzzzzz" in chat window. When I hit enter, nothing happen. I Can't have any interaction with the quests and screen.

Also, I want to help you translate the addon to french, please give me a base to work on, I never did this before (and I am a noob at programming).

Regards,

Ben

**Comment by benoitheylens** [comment] 2016-09-04 14:29
Happened again.
I play with Real UI.

For example, when I had a quest where a little demon asked me to collect things for him, I did it. Then a quest automatically pops because I ended collecting the goods for him, I accepted the next quest, clicking "accept", continue, "accept". Then the game is stuck. I can play, but I can't chat nor click anymore on anything (bags, etc).

Very annoying and barely usable :-/. I am very sad because your addon adds the little thing I needed while leveling :) !

**Comment by benoitheylens** [comment] 2016-09-04 20:38
I did manage to get out of this situation by clicking on the quest again, and then the addon popped the quest screen and I was able to continue.

Still very annoying and feels "buggy"

**Comment by Lanrutcon** [comment] 2016-09-05 01:31
Hello.

I think the problem you describe was caused in the version 1.3. Some players reported a similar error and pointed out that version 1.2 was working correctly.

I reverted back some changes. Please download the latest version (v1.3.1) and check out if the problem still persists.

About the translate. I have in mind to translate to other languages, but until then I want to polish a little bit more.
If you are still interested by then, I'll contact you to do the French translation.

**Comment by chevex** [comment] 2016-09-05 02:33
I am experiencing this bug as well. Quick tip for getting out of it is to press F10 which hides the addon. Even though you can't see it when it's glitching out, the addon is still there preventing you from clicking through it. Pressing F10 followed by escape will hide the glitched addon window and clear any other dialogs away and all should be normal after that.

Since I have a workaround for this occasional bug I'm going to keep playing Legion with this addon, but if I encounter too many more of them too often then I'll probably ditch it and go back to storyline for now.

**Comment by benoitheylens** [comment] 2016-09-05 10:04
Thank you for your quick reaction. @chevex : F10 is binded to my bags on my UI, it does not do anything with addons. The only way I could fix it was to move away from the npc and take the quest back. It happens when there is a natural chaining in quest (you go to see Malfurion from Kadghar and when you arrive, you just have to check in and "thank you" him ;) and the quest he gaves you after that is bugged, you have to do the little trick.).
Anyway, I'll install the 1.3.1 and give you a feedback.
I translated the addon for me. Can't you just add a locale with ACE3 libs ? I'll do the rest ;)

**Comment by chevex** [comment] 2016-09-05 18:58
Right, I'm just going off the readme where it says if you get stuck to use F10, which worked for me since I didn't have it bound to anything else. It seems to hide CTW altogether and let me clear the open quest windows and then start again. After starting again it usually works correctly for me but I have to do this fix every time it happens.

**Comment by Lanrutcon** [comment] 2016-09-05 19:43
When CTW is "ON", the keys do different stuff. For example, if you have "A" keybinded to "Turn Left", you won't start turning left but instead changing between "Accept/Decline" options.

So, if you press F10 when CTW is "ON", the addon will hide itself. If not, something is wrong.

Also, a new version is now available (v1.3.2). Please report back if the problem is still there.

**Comment by benoitheylens** [comment] 2016-09-06 09:20
Hi there, so far so good, I did not encounter bad behavior. At most I get the "old" way to select my quest but I prefer this than to be stuck ...

**Comment by benoitheylens** [comment] 2016-09-11 05:49
I think you can close this point, to be fair, you did an amazing job with the 1.4 !

**Comment by Lanrutcon** [comment] 2016-09-15 20:44
Thanks you.

Fixed in: https://github.com/Lanrutcon/CatchTheWind/commit/2c8c173089f88182d03eabcd014067bb0ab1a066

**Closed by Lanrutcon** 2016-09-15 20:44 UTC
